networks:
  application:
    driver: bridge
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mybackend
    ports:
      - 8000:8000
    volumes:
      - ./:/app
    networks:
      - application
    environment:
      - DB_CONNECTION=sqlite
    entrypoint: ['/bin/sh', '-c']
    command:
      - |
        php artisan serve --host=0.0.0.0 --port=8000
        
  scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: scheduler

    volumes:
      - ./:/app
    networks:
      - application
    environment:
      - DB_CONNECTION=sqlite
    entrypoint: ['/bin/sh', '-c']
    command:
      - |
        php artisan schedule:work

