networks:
  application:
    driver: bridge
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - 8000:8000
    volumes:
      - ./:/app
    networks:
      - application
    environment:
      - DB_CONNECTION=sqlite
    depends_on:
      - scheduler
      - queue
    entrypoint: ['/bin/sh', '-c']
    command:
      - |
        composer install
        composer update
        php artisan key:generate
        php artisan migrate:fresh
        php artisan serve --host=0.0.0.0 --port=8000

  scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: scheduler
    restart: unless-stopped
    volumes:
      - ./:/app
    networks:
      - application
    environment:
      - DB_CONNECTION=sqlite
    entrypoint: ['/bin/sh', '-c']
    command:
      - |
        php artisan schedule:work
  
  queue:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: queue_worker

    restart: unless-stopped

    volumes:
      - ./:/app
    networks:
      - application
    environment:
      - DB_CONNECTION=sqlite
    entrypoint: ['/bin/sh', '-c']
    command:
      - |
        php artisan schedule:work

